#pragma config(Sensor, S1,     MSMTRMX,        sensorI2CCustomFastSkipStates)
#pragma config(Sensor, S2,     MSRXMUX,        sensorI2CCustomFastSkipStates9V)
#pragma config(Motor,  motorA,          TrackSwitch,   tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/**
 * mindsensors-rcxsensorsmux.h provides an API for the Mindsensors RCX Sensor MUX Sensor.  This program
 * demonstrates how to use that API.
 *
 * Changelog:
 * - 0.1: Initial release
 * - 0.2: More comments
 *
 * Credits:
 * - Big thanks to Mindsensors for providing me with the hardware necessary to write and test this.
 *
 * License: You may use this code as you wish, provided you give credit where it's due.
 *
 * THIS CODE WILL ONLY WORK WITH ROBOTC VERSION 4.10 AND HIGHER

 * Xander Soldaat (xander_at_botbench.com)
 * 28 November 2009
 * version 0.2
 */

#include "mindsensors-rcxsensorsmux.h"
#include "mindsensors-rcxmotormux.h"

task main () {

  short chan1 = 0;
  short chan2 = 0;
  short chan4 = 0;
  short chan1_state = 0;
  short chan2_state = 0;
//  short chan4_state = 0;
  short power = 255;

  displayCenteredTextLine(0, "Mindsensors");
  displayCenteredBigTextLine(1, "RXMUX");
  displayCenteredTextLine(3, "Test 1");

  sleep(2000);

  // Set up channel 1 on the RCX sensor MUX to a light sensor in percentage mode
  MSRXMUXsetupChan(MSRXMUX, 1, sensorReflection, modePercentage, 1);

  // Set up channel 2 on the RCX sensor MUX to a touch sensor in raw mode
  MSRXMUXsetupChan(MSRXMUX, 2, sensorTouch, modeRaw, 1);

  // Set up channel 4 on the RCX sensor MUX to rotation sensor in rotation mode
  MSRXMUXsetupChan(MSRXMUX, 4, sensorRotation, modeRotation, 5);

  while(true) {
    // Read from the channels and display
    chan1 = MSRXMUXreadChan(MSRXMUX, 1);
    chan2 = MSRXMUXreadChan(MSRXMUX, 2);
    chan4 = MSRXMUXreadChan(MSRXMUX, 4);

    if(chan1 > 40 && chan1_state == 0) {
    	displayBigTextLine(1, "%d", chan1);
    	chan1_state = 1;
    	MSMTRMX_Control (MSMTRMX, MSMTRMX_M4, power);
  	}
  	else if(chan1 < 40 && chan1_state == 1) {
  		displayBigTextLine(1, "%d", chan1);
    	chan1_state = 0;
    	// reverse motor
  		MSMTRMX_Control (MSMTRMX, MSMTRMX_M4, -power);
  		sleep(20);
    	//brake motor
    	MSMTRMX_Brake (MSMTRMX, MSMTRMX_M4, power);
    	sleep (100);
    	MSMTRMX_Control (MSMTRMX, MSMTRMX_M4, 0);
  	}
  	if(chan2 > 0 && chan2_state == 0) {
  		displayBigTextLine(3, "%d", chan2);
  		chan2_state = 1;
  		//run motor channel 4
  		MSMTRMX_Control (MSMTRMX, MSMTRMX_M1, power);
  	}
  	else if(chan2 < 1 && chan2_state == 1) {
  		displayBigTextLine(3, "%d", chan2);
  		chan2_state = 0;
  		// reverse motor
  		MSMTRMX_Control (MSMTRMX, MSMTRMX_M1, -power);
  		sleep(20);
    	//brake motor
    	MSMTRMX_Brake (MSMTRMX, MSMTRMX_M1, power);
    	sleep (100);
    	MSMTRMX_Control (MSMTRMX, MSMTRMX_M1, 0);
  	}

    //displayBigTextLine(5, "%d", chan4);
  }

  playSound(soundBeepBeep);
  while(bSoundActive) sleep(1);
  eraseDisplay();
  while(1) sleep(1);

}
